name: al_quran
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - data/daftar-surat.json
    - data/surat/1.json
    - data/surat/2.json
    - data/surat/3.json
    - data/surat/4.json
    - data/surat/5.json
    - data/surat/6.json
    - data/surat/7.json
    - data/surat/8.json
    - data/surat/9.json
    - data/surat/10.json
    - data/surat/11.json
    - data/surat/12.json
    - data/surat/13.json
    - data/surat/14.json
    - data/surat/15.json
    - data/surat/16.json
    - data/surat/17.json
    - data/surat/18.json
    - data/surat/19.json
    - data/surat/20.json
    - data/surat/31.json
    - data/surat/32.json
    - data/surat/33.json
    - data/surat/34.json
    - data/surat/35.json
    - data/surat/36.json
    - data/surat/37.json
    - data/surat/38.json
    - data/surat/39.json
    - data/surat/40.json
    - data/surat/41.json
    - data/surat/42.json
    - data/surat/43.json
    - data/surat/44.json
    - data/surat/45.json
    - data/surat/46.json
    - data/surat/47.json
    - data/surat/48.json
    - data/surat/49.json
    - data/surat/50.json
    - data/surat/51.json
    - data/surat/52.json
    - data/surat/53.json
    - data/surat/54.json
    - data/surat/55.json
    - data/surat/56.json
    - data/surat/57.json
    - data/surat/58.json
    - data/surat/59.json
    - data/surat/60.json
    - data/surat/61.json
    - data/surat/62.json
    - data/surat/63.json
    - data/surat/64.json
    - data/surat/65.json
    - data/surat/66.json
    - data/surat/67.json
    - data/surat/68.json
    - data/surat/69.json
    - data/surat/70.json
    - data/surat/71.json
    - data/surat/72.json
    - data/surat/73.json
    - data/surat/74.json
    - data/surat/75.json
    - data/surat/76.json
    - data/surat/77.json
    - data/surat/78.json
    - data/surat/79.json
    - data/surat/80.json
    - data/surat/81.json
    - data/surat/82.json
    - data/surat/83.json
    - data/surat/84.json
    - data/surat/85.json
    - data/surat/86.json
    - data/surat/87.json
    - data/surat/88.json
    - data/surat/89.json
    - data/surat/90.json
    - data/surat/91.json
    - data/surat/92.json
    - data/surat/93.json
    - data/surat/94.json
    - data/surat/95.json
    - data/surat/96.json
    - data/surat/97.json
    - data/surat/98.json
    - data/surat/99.json
    - data/surat/100.json
    - data/surat/101.json
    - data/surat/102.json
    - data/surat/103.json
    - data/surat/104.json
    - data/surat/105.json
    - data/surat/106.json
    - data/surat/107.json
    - data/surat/108.json
    - data/surat/109.json
    - data/surat/110.json
    - data/surat/111.json
    - data/surat/112.json
    - data/surat/113.json
    - data/surat/114.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: arabic
      fonts:
        - asset: assets/fonts/LPMQ.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
